### ISSUE TITLE
nsfwjs model error

### ISSUE THREAD

**Issue by seramat** [x-dr/nsfwjs-api#1]
Docker部署，不停重启，logs 显示
```
/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8293
                            throw new Error("Request to " + this.path + " failed with status code " +
                                  ^

Error: Request to https://nsfwjs.com/model/model.json failed with status code 404. Please verify this URL points to the model JSON of the model to load.
    at HTTPRequest.<anonymous> (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8293:35)
    at step (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:125:27)
    at Object.next (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:74:53)
    at fulfilled (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:55:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

请问如何解决？谢谢

**Comment by x-dr** [comment]
添加环境变量 `MODEL_URL`
```shell
docker run -itd \
           --name nsfwjs \
            -p 3035:3035 \
            -e MODEL_URL=https://raw.githubusercontent.com/x-dr/nsfwjs-api/main/models/model.json \
           --restart=always \
           gindex/nsfwjs-api:latest
```

**Comment by seramat** [comment]
谢谢。可以了
